# Generated by Django 5.1.4 on 2024-12-16 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_students_remove_uploadedfile_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='roll_no',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='student_photos/'),
        ),
    ]
