# Generated by Django 5.1.4 on 2024-12-18 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_students_roll_no_alter_students_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
            ],
        ),
        migrations.AlterField(
            model_name='students',
            name='roll_no',
            field=models.CharField(max_length=25, null=True, unique=True),
        ),
        migrations.AlterModelTable(
            name='students',
            table='Student Details',
        ),
        migrations.AlterModelTable(
            name='uploadedfile',
            table='Uploaded & Processed Files',
        ),
        migrations.CreateModel(
            name='ClassroomGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('classroom_image', models.ImageField(upload_to='classroom_images/')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.course')),
            ],
            options={
                'db_table': 'Classroom photos',
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent')], default='Absent', max_length=10)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='attendance_photos/')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.students')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.course')),
            ],
            options={
                'db_table': 'attendance_records',
                'unique_together': {('date', 'course', 'student')},
            },
        ),
    ]
